### PR TITLE
update WIN32 sig for GetCSGOInput

### PR DESCRIPTION
**Pull request by frankie48**
updated the windows signature for getcsgoinput to the latest version of client.dll. I don't use linux so I didn't grab the sig for it

### CODE REVIEW

**Comment by Cyk-Fad** [comment]
Hey bro,could u plz give me a DISCORD or others.If u can teach me how to update the offset or tell me the offset,i would pay for this.Thanks a lot

**Comment by frankie48** [comment]
update what offset? put your discord i'll add you later.

**Comment by Cyk-Fad** [comment]
> update what offset?

After my testing,my version of the source,when i inject dll,game crashed lol

**Comment by Cyk-Fad** [comment]
> update what offset? put your discord i'll add you later.

Do u know any updated offsets?

**Comment by Cyk-Fad** [comment]
> update what offset? put your discord i'll add you later.

Okay thanks,My discord is Ap15#2025

**Pull request closed without merging**
